name = "Titanium Developers Modpack"
author = "rotgruengelb"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d23ec9b677936528862c5ee86922cf759da4cbffd4b010fa43bcc5b93d66c817"

[versions]
fabric = "0.17.1"
minecraft = "1.21.1"
