name = "Titanium Developers Modpack"
author = "rotgruengelb"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1298f787954bb0170c2c44e9ab34291f5e716a8688df068786c7f07f64863557"

[versions]
fabric = "0.17.1"
minecraft = "1.21.1"
